- name: Create All Robosshop Parameters
  hosts: localhost
  tasks:
    - name: Create value
      community.aws.aws_ssm_paramater_store:
        name: "param.dev.catalogue.MONGO"
        value: "false"
        region: "us-east-1"