- name: Add Roboshop Application User
  when: APP_USER is defined
  ansible.builtin.user:
    name: "{{ APP_USER }}"

- name: Remove Previous Version of App
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state: absent

- name: Download App Content & Extracting File
  ansible.builtin.unarchive:
    src: https://github.com/raghudevopsb69/{{COMPONENT}}/archive/refs/heads/main.zip
    dest: "/tmp"
    remote_src: yes

- name: Copy Extracted App Content to App location
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: "{{ APP_LOC }}/"
    remote_src: yes